service: baas

provider:
  name: aws
  region: ca-central-1
  runtime: nodejs10.x

functions:
  hello:
    handler: dist/handler.hello
    layers:
      - arn:aws:serverlessrepo:us-east-1:145266761615:applications/image-magick-lambda-layer
    events:
      - http:
          path: hello
          method: GET
          cors: true
