service: baas

provider:
  name: aws
  region: ca-central-1
  runtime: nodejs10.x

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true
